apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            - run
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared
      volumes:
        - name: config
          configMap:
            name: cloudflared
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: monitoring
data:
  config.yaml: |
    
    tunnel: grafana

    credentials-file: /etc/cloudflared/creds/credentials.json

    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:2000
    no-autoupdate: true

    ingress:
    - hostname: grafana.williamalvarez.dev
      service:  http://kube-prometheus-stack-grafana:80
      
    - hostname: hello.example.com
      service: hello_world
    # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
    - service: http_status:404
